language: python

python:
  - "3.6"

os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenmpi-dev
    - openmpi-bin

git:
  depth: 3

cache:
  apt: true


install:
  - pip install -e '.[docs,tests]'

script:
  - ./run_tests.sh

branches:
  only:
  - master
  - develop