language: python

python:
  - "3.6"

os: linux

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libopenmpi-dev
    - openmpi-bin

git:
  depth: 3

cache:
  apt: true

before_install:
# We need GraphViz to draw figures of graphs and lattices:
  - sudo apt-get install graphviz
install:
  - pip install -e '.[docs,tests,analytics]'
  - pip install tensorflow==1.13.1 keras
  - pip install codecov pytest-cov

script:
  - ./run_tests.sh

branches:
  only:
  - master
  - develop

after_success:
  - codecov
